backend:
  name: github
  repo: tsiro66/despoina-site
  branch: main
  base_url: https://sveltia-cms-auth.theogr99.workers.dev

media_folder: src/assets/projects
public_folder: /src/assets/projects

collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    format: json
    extension: json
    nested:
      depth: 1
    meta: { path: { widget: string, label: Path, index_file: index } }
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Photo, name: image, widget: image, required: true }
      - { label: Description, name: description, widget: text, required: true }
      - { label: Start Date, name: dateStart, widget: datetime, date_format: "YYYY-MM-DD", time_format: false, required: true }
      - { label: End Date, name: dateEnd, widget: datetime, date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: Order, name: order, widget: number, value_type: int, min: 1, required: true }
